---
- hosts: 172.31.41.130
  become: True
  tasks:
    - name: install packages
      yum:
         name: "{{item.name}}"
         state: "{{item.state}}"
      loop: 
         - {name: "git", state: "present"}
         - {name: "docker", state: "present"}
         - {name: "httpd", state: "present"} 
... 
